name: Build Package

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run:
          pnpm run lint
      - name: Test
        run: pnpm test
      - name: Create npm package
        run: pnpm pack
